# Generated by Django 5.1 on 2024-10-17 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=20)),
                ('release_date', models.TimeField()),
                ('rating_field', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=1)),
                ('musician_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.musicians')),
            ],
        ),
    ]
