# Generated by Django 5.1 on 2024-10-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('select_ins', models.CharField(choices=[('G', 'Guiter'), ('T', 'Tom Tom'), ('D', 'Drum'), ('H', 'Harmonium'), ('P', 'Piano')], max_length=1)),
            ],
        ),
    ]
