# Generated by Django 5.1 on 2024-10-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicians',
            name='middle_name',
        ),
    ]
