# Generated by Django 5.1.5 on 2025-02-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='colour',
            field=models.CharField(blank=True, choices=[('Black', 'BLACK'), ('White', 'WHITE'), ('Brown', 'BROWN'), ('Gray', 'GRAY'), ('Red', 'RED'), ('Tabby', 'TABBY'), ('Tortoiseshell', 'TORTOISESHELL'), ('Calico', 'CALICO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='rating',
            field=models.CharField(choices=[('⭐', '⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐')], max_length=10),
        ),
    ]
