# Generated by Django 5.1 on 2025-01-05 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userbankaccount_account_type'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('receive_money', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_receive', to='accounts.userbankaccount')),
                ('send_money', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_send', to='accounts.userbankaccount')),
            ],
        ),
    ]
