# Generated by Django 5.1 on 2025-01-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_receive_money_moneytransfer_receivemoney_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'Withdrawal'), (3, 'Loan'), (4, 'Loan Paid'), (5, 'Send money'), (6, 'Receive money')], null=True),
        ),
        migrations.DeleteModel(
            name='MoneyTransfer',
        ),
    ]
