# Generated by Django 5.1 on 2025-01-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_bank_bankrupt',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
