# Generated by Django 5.1 on 2024-10-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcategory', '0002_rename_categorrymodel_categorymodel'),
        ('taskmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task_cate',
            field=models.ManyToManyField(to='taskcategory.categorymodel'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='assign_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
