# Generated by Django 5.1 on 2024-10-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmodel', '0002_taskmodel_task_cate_alter_taskmodel_assign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='assign_date',
            field=models.DateTimeField(),
        ),
    ]
