# Generated by Django 5.1 on 2024-10-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmodel', '0003_alter_taskmodel_assign_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='titel',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='assign_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
