# Generated by Django 5.1 on 2024-10-28 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskcategory', '0001_initial'),
        ('taskmodel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategorryModel',
            new_name='CategoryModel',
        ),
    ]
