# Generated by Django 5.1.5 on 2025-02-06 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_categories_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(choices=[('Black', 'BLACK'), ('White', 'WHITE'), ('Brown', 'BROWN'), ('Gray', 'GRAY'), ('Red', 'RED'), ('Tabby', 'TABBY'), ('Tortoiseshell', 'TORTOISESHELL'), ('Calico', 'CALICO')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='addpost/images')),
                ('price', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=20)),
                ('contact', models.CharField(max_length=12)),
                ('description', models.TextField()),
                ('age', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categories')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.origin')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐'), ('⭐⭐', '⭐⭐'), ('⭐', '⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐')], max_length=10)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
