# Generated by Django 5.1.5 on 2025-02-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpost', '0002_alter_post_colour_alter_post_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='rating',
            field=models.CharField(choices=[('⭐', '⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐')], max_length=10),
        ),
    ]
